# Permalinks
#
permalink:           pretty

# Setup
title:               'gaodq'
tagline:             '/var/log/message'
description:         '(/¯◡ ‿ ◡)/¯ ~ ┻━┻'
url:                 https://gaodq.github.io
baseurl:             ''
paginate:            5

markdown:            kramdown

# About/contact
author:
  name:              gaodq
  url:               https://gaodq.github.io
  email:             gaodq7c7@gmail.com
  github:            https://github.com/gaodq


# Custom vars
version:             1.0.0
plugins: [jekyll-paginate]
