# Permalinks
#
permalink:           pretty

# Setup
title:               gaodq
tagline:             'Blog'
# description:       ''
url:                 https://gaodq.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              gaodq
  url:               https://gaodq.github.io
  email:             gaodq7c7@gmail.com
  github:            https://github.com/gaodq


# Custom vars
version:             1.0.0
gems: [jekyll-paginate]
